# Generated by Django 5.1.1 on 2024-09-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designerdetails',
            name='portfolio_link',
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='designerdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('designer', 'designer'), ('user', 'user')], default='user', max_length=100),
        ),
    ]
