# Generated by Django 5.1.1 on 2024-09-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
        ('users', '0002_remove_designerdetails_portfolio_link_and_more'),
    ]

    operations = [
    ]
