# Generated by Django 5.1.1 on 2024-09-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='categories',
        ),
    ]
